ddns-scripts: add send-update package
kn-gl/packages pull request #10
Opened 2024-02-21 14:17 UTC by SPiskurskyi

Added a tool that makes a request to the dynamic DNS service to update information, similar to the curl/wget tools (GET request)

Reference: OWF-2871

2024-03-05 07:33 UTC, septimomend commented
Looks ok, but reassigned for deeper review

2024-03-05 18:34 UTC, s-skorobreshchuk commented
Technical implementation is good.
But, changes doesn't make sense for me... We need to remove curl to not provide security breach to perform HTTP requests, and that's why we implemented our own binary that making HTTP requests and that using curl library under the hood....
For me it doesn't fix a security breach, but also adds extra code that we need to maintain potentially (even if it is so easy now)...

@MykolaKopanyshyn @septimomend what do you think? I believe we shouldn't provide any binary that makes HTTP requests, or leave the standard curl if we anyway need it...

2024-03-06 11:01 UTC, MykolaKopanyshyn commented on net/ddns-scripts/src/send-update.c
> +    curl_easy_setopt(curl, CURLOPT_URL, argv[1]);
Is it working?

Your libcurl program just download provided URL.
Could you provide me an example how send-update is used(params and co).

To my understanding, curl is used to update(i.e. upload) current IP address of the DDNS client to the server.
So, how it is working???

2024-03-06 11:03 UTC, MykolaKopanyshyn requested changes

2024-03-06 11:03 UTC, MykolaKopanyshyn commented on net/ddns-scripts/src/send-update.c
> +    if(res != CURLE_OK)
The main idea of using our binary instead or curl - to remove possibility to download something to the CPE using curl.
So, I would rather expect some kind of hardcoded list of URL we can work with.

2024-03-11 10:10 UTC, SPiskurskyi commented on net/ddns-scripts/src/send-update.c
> +    curl_easy_setopt(curl, CURLOPT_URL, argv[1]);
Example of a GET request using a newer version:
ddns-sendupdate "http://gurucam:teiltest@dynupdate.noip.com/nic/update?hostname=lwglo.ddns.net&myip=127.0.0.1"

2024-03-11 10:27 UTC, SPiskurskyi commented on net/ddns-scripts/src/send-update.c
> +    if(res != CURLE_OK)
done in https://github.com/kn-gl/feed-owf/pull/26

2024-03-11 10:28 UTC, SPiskurskyi commented
The main implementation moved to https://github.com/kn-gl/feed-owf/pull/26

2024-03-12 09:03 UTC, s-skorobreshchuk approved these changes

2024-03-20 15:55 UTC, merged