packages: gpgme and libassuan GPL version correction
kn-gl/packages pull request #5
Opened 2024-01-09 14:44 UTC by SPiskurskyi

References: OWF-2685

2024-01-09 16:54 UTC, MykolaKopanyshyn requested changes

2024-01-09 16:54 UTC, MykolaKopanyshyn commented on libs/libassuan/Makefile
> -PKG_LICENSE:=GPL-3.0-or-later
Why not `LGPL-2.1`

2024-01-09 16:54 UTC, MykolaKopanyshyn commented on libs/libassuan/Makefile
>  PKG_LICENSE_FILES:=COPYING
`COPYING` is for the tool and it is GPLv3.
We are using lib, so please change to `COPYING.LIB` - it is GPLv2.1

2024-01-09 16:54 UTC, MykolaKopanyshyn commented on libs/gpgme/Makefile
> +PKG_LICENSE:=LGPL-2.1-or-later
Why not `GPLv2` as in the file `COPYING`

2024-01-10 15:33 UTC, MykolaKopanyshyn commented on libs/gpgme/Makefile
> +PKG_LICENSE:=LGPL-2.1-or-later
Maybe my comment is not clear.
We have 2 lines:
```
PKG_LICENSE:=LGPL-2.1-or-later
PKG_LICENSE_FILES:=COPYING
```
That means that package has license `LGPL-2.1-or-later` which could be find in file `COPYING`
I opened file `COPYING` and in this file I see that license is `LGPL-2`

So, the question is: why `LGPL-2.1-or-later` and not `LGPL-2`

2024-01-10 15:33 UTC, MykolaKopanyshyn commented on libs/libassuan/Makefile
> -PKG_LICENSE:=GPL-3.0-or-later
Any comment?

2024-01-10 15:33 UTC, MykolaKopanyshyn commented on libs/libassuan/Makefile
>  PKG_LICENSE_FILES:=COPYING
Any comment???

2024-01-10 15:40 UTC, SPiskurskyi commented on libs/libassuan/Makefile
> -PKG_LICENSE:=GPL-3.0-or-later
fixed

2024-01-10 15:40 UTC, SPiskurskyi commented on libs/libassuan/Makefile
>  PKG_LICENSE_FILES:=COPYING
fixed

2024-01-10 15:40 UTC, SPiskurskyi commented on libs/gpgme/Makefile
> +PKG_LICENSE:=LGPL-2.1-or-later
Yeah, i got u, my comment above is not related to this thread, this comment is just like general proposal to you.

2024-01-11 08:40 UTC, MykolaKopanyshyn requested changes

2024-01-11 08:40 UTC, MykolaKopanyshyn commented on libs/gpgme/Makefile
> +PKG_LICENSE:=LGPL-2.1
Please, provide strong argument what should be used `LGPL-2.1`,  `LGPL-2.1-only` or `LGPL-2.1-or-later`

2024-01-11 08:40 UTC, MykolaKopanyshyn commented on libs/gpgme/Makefile
> +PKG_LICENSE_FILES:=COPYING.LESSER
Analyze both libs provided by this Makefile and chose license shared between(if applicable)

2024-01-11 14:23 UTC, SPiskurskyi commented on libs/gpgme/Makefile
> +PKG_LICENSE:=LGPL-2.1
In my opinion we should use `PKG_LICENSE:=LGPL-2.1-or-later` and `PKG_LICENSE_FILES:=COPYING.LESSER` because:
- We including and compiling only two packages: libgpgme and libgpgmepp(C++ version). All source code, except gpgme-tool(which are not included) have `SPDX-License-Identifier: LGPLv2.1-or-later ` comments, so I can assume that the license for those libraries should be the same.
- `PKG_LICENSE_FILES:=COPYING.LESSER`  must be used because code which is covered in COPYING (GPLv3) are not used as i described above.
- Also a good example would be the lxc package, where the Makefile says `PKG_LICENSE_FILES:=COPYING LICENSE.GPL2 LICENSE.LGPL2.1`, `PKG_LICENSE:=LGPL-2.1-or-later BSD-2-Clause GPL-2.0 ` which, unlike gpgme, specifies multiple licenses and multiple license files.

2024-01-12 08:29 UTC, merged